analytics: {}
color:
  brandColors:
    - '#4C4C4C'
    - '#727272'
    - '#C3B8B2'
    - '#040000'
    - '#FDFCF8'
  brandStrength: 0.8125
  lightness: 1
  rhythmicContrast: 0.75
  saturation: 0.375
cta: {}
layout_spectrum: 0.798519
name: Lady Rebel
opengraph: {}
purpose: []
typography_spectrum: 0.91119
